# Generated by Django 2.1.5 on 2019-01-21 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dummy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obf',
            old_name='content',
            new_name='obf_content',
        ),
    ]
