# Generated by Django 2.1.5 on 2019-01-22 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dummy', '0002_auto_20190121_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obf',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
