# Generated by Django 2.1.5 on 2019-01-26 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Dummy', '0003_auto_20190122_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='OBZ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obz_content', models.TextField()),
                ('isPrivate', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('locale', models.TextField()),
                ('license', models.TextField()),
                ('author', models.TextField()),
                ('author_url', models.TextField()),
                ('source_url', models.TextField()),
                ('extension', models.TextField()),
                ('image_url', models.TextField()),
                ('isPrivate', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
